[package]
name = "mountpoint-sqs"
version = "0.1.0"
edition = "2021"
authors = ["Paulo Almeida"]

[dependencies]
fuser = "0.14.0"
libc = "0.2.159"
clap = { version = "4.5.20", features = ["cargo", "derive"] }
env_logger = "0.11.5"
procfs = "0.17.0"
log = "0.4.22"
anyhow = "1.0.90"
aws-config = "1.5.1"
aws-sdk-sqs = "1.30.0"
tokio = { version = "1.40.0", features = ["full"] }
url = "2.5.2"
